### ISSUE TITLE
Roadmap to Specification

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/FirstPhoneBook#1]
### Introduction

- [ ] Read [Introduction]( .... /doc/Introduction/Introduction.md)

### Collaboration

- [ ] Read [Introduction to Git and GitHub](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/Introduction2Git/Introduction2Git.md)
- [ ] Read [Workflow for Contributing](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/WorkflowForContributing/WorkflowForContributing.md)
- [ ] Read [GitFlow Workflow](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/GitFlowWorkflow/GitFlowWorkflow.md)
- [ ] Read Issue #(A), create own GitHub account and close the issue
- [ ] Read Issue #(B), install Git and close the issue
- [ ] Read Issue #(C), install Visual Studio Code and close the issue
- [ ] Read Issue #(D), connect Visual Studio Code with GitHub and close the issue
- [ ] Make yourself familiar with the [Basic Syntax of Markdown](https://www.markdownguide.org/basic-syntax/)
- [ ] Read [Formulating Issues](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/FormulatingIssues/FormulatingIssues.md)
- [ ] Read [Formulating Commit and Merge Request Messages](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/FormulatingCommitMessages/FormulatingCommitMessages.md)
- [ ] Read [Management of Conflicts](https://github.com/openBackhaul/ApplicationPattern/blob/tsi/doc/PreparingSpecifying/ConflictManagement/ConflictManagement.md)
- [ ] Read Issue #(E), contribute to Content of Introduction

### API Specification
